elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'
  extraEnvs:
  - name: discovery.type
    value: single-node
  - name: cluster.initial_master_nodes
    value: null
